name: publish image

on:
  push:
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/avinal/fauxpilot:latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build the lark Docker image
        run: docker build https://github.com/moyix/fauxpilot.git#:converter --tag $IMAGE_NAME

      - name: Push lark to GitHub Container Registry
        run: docker push $IMAGE_NAME